version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
#  db:
#    image: mysql:5.7.22
#    restart: always
#    environment:
#      MYSQL_DATABASE: ambassador
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - .dbdata:/var/lib/mysql
#    ports:
#      - "33066:3306"
  db:
    image: postgres
    environment:
      POSTGRES_DB: ambassador
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - .db:/var/lib/postgres
    ports:
      - "54322:5432"
    restart: always
  redis:
    image: redis:latest
    ports:
      - 6379:6379


volumes:
  db:
    driver: local